import moment from 'moment';
/**
 * Queries used in creating relevant tables
 */

const createQueries = {

  // Users table
  usersTable: `
    CREATE TABLE IF NOT EXISTS
     users(
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      firstname VARCHAR(255) NOT NULL,
      lastname VARCHAR(255) NOT NULL,
      email VARCHAR(100) NOT NULL,
      password VARCHAR(255) NOT NULL,
      gender CHAR(1),
      image VARCHAR(255),
      phone_no VARCHAR(15) NOT NULL,
      registered_on TIMESTAMP NOT NULL DEFAULT NOW(),
      is_admin BOOLEAN NOT NULL DEFAULT false,
      is_vendor BOOLEAN NOT NULL DEFAULT false,
      created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `,

  // Follow table
  followTable: `
    CREATE TABLE IF NOT EXISTS
    follow (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      follower_id INT REFERENCES users (id) ON DELETE CASCADE,
      following_id INT REFERENCES users (id) ON DELETE CASCADE,
      created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `,

  // Posts table
  postsTable: `
    CREATE TABLE posts (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      pictures VARCHAR(255) DEFAULT NULL,
      audio VARCHAR(255) DEFAULT NULL,
      title VARCHAR(255) DEFAULT NULL,
      caption varchar(200) NOT NULL DEFAULT '',
      post_type VARCHAR(255),
      user_id INT REFERENCES users (id) ON DELETE CASCADE,
      post_relation_post_id INT DEFAULT NULL,
      post_relation_user_id INT REFERENCES users (id) ON DELETE CASCADE,
      reposts INT DEFAULT '0',
      created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `,

  // Post likes table
  postLikesTable: `
    CREATE TABLE post_likes (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      post_id INT REFERENCES posts (id) ON DELETE CASCADE,
      user_id INT REFERENCES users (i d) ON DELETE CASCADE
    )
  `,

  // Messages table
  messagesTable: `
    CREATE TABLE 
    messages (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      sender_id REFERENCES users (id) ON DELETE CASCADE,
      receiver_id REFERENCES users (id) ON DELETE CASCADE,
      message TEXT NOT NULL,
      created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
      msg_type TEXT NOT NULL,
      media_url TEXT
    )
  `,

  // Comments table
  commentsTable:`
    CREATE TABLE IF NOT EXISTS
    comments (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INT REFERENCES users (id) ON DELETE CASCADE,
      post_id INT REFERENCES posts (id) ON DELETE CASCADE,
      comment_text TEXT NOT NULL,
      created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP
    )
   `,

  // Comment likes table
  commentLikesTable:`
    CREATE TABLE IF NOT EXISTS
    comment_likes (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INT NOT NULL,
      comment_id INT REFERENCES comments (id) ON DELETE CASCADE
    )
  `,

  // Notifications table
  notificationsTable:`
    CREATE TABLE notifications (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      notification_type VARCHAR(20) NOT NULL,
      userID INT NOT NULL,
      objectID INT NOT NULL
    )
  `,

};

/**
 * Queries used in dropping relevant tables
 */

const dropQueries = {

  // Users table
  usersTable: 'DROP TABLE IF EXISTS users CASCADE',

  // Follow table
  followTable: 'DROP TABLE IF EXISTS follow CASCADE',

  // Post likes table
  postLikesTable: 'DROP TABLE IF EXISTS post_likes CASCADE',

  // Messages table
  messagesTable: 'DROP TABLE IF EXISTS messages CASCADE',

  // Comments table
  commentsTable: 'DROP TABLE IF EXISTS comments CASCADE',

  // Comments table
  commentLikesTable: 'DROP TABLE IF EXISTS comment_likes CASCADE',

  // Notifications table
  notificationsTable: 'DROP TABLE IF EXISTS notificatons CASCADE'

};

const migrateQueries = {

};

/**
 * Queries used in seeding tables
 */

const seedQueries = {

  // Users table
  usersTable: `
    INSERT INTO users(firstname, lastname, email, password, gender, phone_no, registered_on, is_admin, is_vendor)
      VALUES ('chukwudi', 'ume', 'c.ume@gmail.com', '$2b$08$5yWcZIAYmtpSw89Nq3q9p.CZe66iPG91rhI2z.6cbH3YCj1DCogLa', 'm', '08033000000', '${moment().format('YYYY-MM-DD HH:mm')}', true, false),
        ('Ernest', 'Genius', 'e.genius@gmail.com', '$2b$08$5yWcZIAYmtpSw89Nq3q9p.CZe66iPG91rhI2z.6cbH3YCj1DCogLa', 'm', '08033000000', '${moment().format('YYYY-MM-DD HH:mm')}', false, true),
        ('Chike', 'Bad guy', 'c.guy@gmail.com', '$2b$08$5yWcZIAYmtpSw89Nq3q9p.CZe66iPG91rhI2z.6cbH3YCj1DCogLa', 'm', '08033000000', '${moment().format('YYYY-MM-DD HH:mm')}', false, false),
        ('Gilbert', 'Good guy', 'g.guy@gmail.com', '$2b$08$5yWcZIAYmtpSw89Nq3q9p.CZe66iPG91rhI2z.6cbH3YCj1DCogLa', 'm', '08033000000', '${moment().format('YYYY-MM-DD HH:mm')}', false, false),
        ('Christopher', 'Ben', 'c.ben@gmail.com', '$2b$08$5yWcZIAYmtpSw89Nq3q9p.CZe66iPG91rhI2z.6cbH3YCj1DCogLa', 'm', '08033000000', '${moment().format('YYYY-MM-DD HH:mm')}', false, false),
        ('Anand', 'Iswhan', 'a.iswhan@gmail.com', '$2b$08$5yWcZIAYmtpSw89Nq3q9p.CZe66iPG91rhI2z.6cbH3YCj1DCogLa', 'm', '08033000000', '${moment().format('YYYY-MM-DD HH:mm')}', false, false),
        ('Magnus', 'Carlsen', 'm.carlsen@gmail.com', '$2b$08$5yWcZIAYmtpSw89Nq3q9p.CZe66iPG91rhI2z.6cbH3YCj1DCogLa', 'm', '08033000000', '${moment().format('YYYY-MM-DD HH:mm')}', false, false),
        ('Dan', 'Brown', 'd.brown@gmail.com', '$2b$08$5yWcZIAYmtpSw89Nq3q9p.CZe66iPG91rhI2z.6cbH3YCj1DCogLa', 'm', '08033000000', '${moment().format('YYYY-MM-DD HH:mm')}', false, false),
        ('Burna', 'Boy', 'b.boy@gmail.com', '$2b$08$5yWcZIAYmtpSw89Nq3q9p.CZe66iPG91rhI2z.6cbH3YCj1DCogLa', 'm', '08033000000', '${moment().format('YYYY-MM-DD HH:mm')}', false, false)
    `,

  // Follow table
  followTable:`
    INSERT INTO follow (follower_id, following_id, id) VALUES
      (4, 2, 1),
      (9, 4, 2),
      (4, 9, 3),
      (14, 4, 4),
      (4, 10, 5)
  `,

  // Post likes table
  postLikesTable:`
    INSERT INTO post_likes (post_id, user_id, id) VALUES
      (3, 4, 2),
      (4, 2, 3),
      (4, 4, 4),
      (5, 2, 5),
      (6, 4, 11),
      (34, 4, 15),
      (36, 4, 17),
      (8, 9, 23),
      (10, 9, 24),
      (9, 9, 25),
      (2, 9, 26),
      (13, 9, 27),
      (13, 9, 28),
      (6, 9, 29),
      (13, 9, 30),
      (13, 9, 31),
      (13, 9, 32),
      (24, 9, 33),
      (1, 4, 34),
      (38, 4, 35),
      (26, 4, 36),
      (26, 4, 37),
      (0, 4, 40),
      (0, 4, 41),
      (0, 4, 42),
      (46, 4, 43),
      (46, 4, 44),
      (0, 4, 46),
      (0, 4, 47),
      (52, 4, 48)
  `,

  // Messages table
  messagesTable: `
  INSERT INTO messages (messageID, senderID, receiverID, message, created_at, msg_type, media_name) VALUES
    (8, 4, 5, 'hello', '2017-08-22 23:22:27', 'text', ''),
    (9, 5, 4, 'hello back', '2017-08-23 09:37:58', 'text', ''),
    (10, 4, 5, 'how are you?', '2017-08-23 09:41:02', 'text', ''),
    (11, 5, 4, 'great you?', '2017-08-23 09:41:23', 'text', ''),
    (12, 4, 5, 'alright i gues', '2017-08-23 10:38:13', 'text', ''),
    (13, 4, 5, 'How\\'s Tobi?', '2017-08-23 11:42:54', 'text', ''),
    (14, 4, 9, 'First', '2017-08-23 12:22:47', 'text', ''),
    (15, 4, 9, 'test', '2017-08-23 15:57:45', 'text', '')
  `,

  // Comments table
  commentsTable: `
    INSERT INTO comments (comment_id, user_id, post_id, comment, reply_status, reply_post_id, created_at) VALUES
      (1, 1, 1, '1', 0, 0, '2017-05-16 13:24:38'),
      (2, 4, 4, 'Heyo', 0, 0, '2017-05-17 22:42:08'),
      (3, 2, 4, 'hello', 1, 6, '2017-05-18 23:18:43'),
      (4, 4, 46, 'Nice post', 0, 0, '2017-05-21 12:57:22'),
      (5, 4, 46, 'Nice pics though', 0, 0, '2017-05-21 12:59:31'),
      (7, 4, 46, 'lol', 0, 0, '2017-05-21 20:11:12'),
      (8, 4, 46, '@chidishgambino #learn', 0, 0, '2017-06-01 00:30:15'),
      (9, 4, 52, 'what do you guys think?', 0, 0, '2017-06-11 11:13:14'),
      (10, 2, 56, 'This is a comment', 0, 0, '2017-06-25 23:46:07'),
      (11, 4, 46, 'This is a comment', 0, 0, '2017-09-12 16:20:26')
    `,

  // Comment Likes table
  commentLikesTable: `
    INSERT INTO comment_likes (id, user_id, comment_id) VALUES
      (1, 5, 2),
      (2, 6, 2),
      (3, 4, 2)`

};

module.exports = {
  createQueries,
  dropQueries,
  migrateQueries,
  seedQueries,
};
